import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const comicShanns = localFont({
  src: './fonts/comic-shanns.woff2',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={comicShanns.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
